name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: "Run test: validate edge cloud clients instantiation"
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        pytest -v tests/common/test_invoke_edgecloud_clients.py

    - name: "Run test: validate network clients instantiation"
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        pytest -v tests/common/test_invoke_network_clients.py

  lint:
    name: Run linters
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: isort check
      run: isort src tests --check --profile black --filter-files

    - name: black check
      run: black src tests --check

    - name: flake8 check
      run: flake8 src tests
